version: 2.1

orbs:
  node: circleci/node@5.0.3
  aws-cli: circleci/aws-cli@3.1.3

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "Pipfile.lock" }}-{{ checksum "package.json" }}
      - run:
          name: Install python dependencies
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install --upgrade pip pipenv
            pipenv install --deploy --dev
      - run:
          name: Check dependencies
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pipenv check
      - node/install
      - node/install-packages
      - save_cache:
          paths:
            - ./.venv
            - ./node_modules
          key: v2-dependencies-{{ checksum "Pipfile.lock" }}-{{ checksum "package.json" }}

      - run:
          name: Black
          command: pipenv run black-check
      - run:
          name: iSort
          command: pipenv run isort-check
  cdk-synth:
    docker:
      - image: cimg/python:3.10-node
    environment:
      AWS_ACCESS_KEY_ID: "fake"
      AWS_DEFAULT_REGION: "eu-west-2"
      AWS_SECRET_ACCESS_KEY: "fake"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "Pipfile.lock" }}-{{ checksum "package.json" }}
      - aws-cli/setup:
          profile-name: default
      - run:
          name: CDK Synth
          command: |
            source .venv/bin/activate
            ./node_modules/.bin/cdk synth --ci
  deploy:
    docker:
      - image: cimg/python:3.10-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "Pipfile.lock" }}-{{ checksum "package.json" }}
      - run:
          name: CDK Deploy
          command: |
            source .venv/bin/activate
            ./node_modules/.bin/cdk deploy --ci

workflows:
  build-and-test:
    jobs:
      - build-and-test
      - cdk-synth:
          requires:
            - build-and-test
      - deploy:
          name: Deploy
          requires:
            - cdk-synth
          context: [ deployment-production-shared-image-builder ]
          filters: { branches: { only: [ main ] } }
